module.exports = {
  'likes': '{likes, number} me gusta',
  'logout': 'Salir',
  'english': 'Ingles',
  'spanish': 'Español',
  'signup.subheading': 'Regístrate para ver fotos de tus amigos en Gram',
  'signup.facebook': 'Iniciar sesión con Facebook',
  'signup.text': 'Iniciar sesión',
  'email': 'Correo electronico',
  'username': 'Nombre de usuario',
  'fullname': 'Nombre completo',
  'password': 'Contraseña',
  'signup.call-to-action': 'Regístrate',
  'signup.have-account': '¿Tienes una cuenta?',
  'signin': 'Entrar',
  'signin.not-have-account': '¿Aun no tienes una cuenta?',
  'language': 'Idioma',
  'upload-picture': 'Subir imagen',
  'upload': 'Subir'
}
